# Generated by Django 5.2.17 on 2026-09-28 15:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_project_starred_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='stars',
            field=models.ManyToManyField(blank=True, related_name='experience_stars', to=settings.AUTH_USER_MODEL),
        ),
    ]
